name: xhs-tool
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - PyQt5
      - openpyxl
      - pyinstaller
      - Pillow
      - rembg
      - onnxruntime